config/routes.rb
Rails.application.routes.draw do
  resources :charts

end

app/models/chart.rb
class Chart < ActiveRecord::Base

  has_attached_file :photo, :default_url => 'missing.png'
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]

  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.all
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
  end

  # GET /charts/new
  def new
    @chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Chart.new(chart_params)
    filename  = SecureRandom.urlsafe_base64 + '.png'
    dir_path  = File.join(Rails.root, "photos_temp")
    gnuploter = Gnuploter::Gnuplot.new
    gnuploter.title = 'New chart'
    gnuploter.plot_to_png("[-10:10] sin(x)", filename, dir_path)

# TO DO change sleep
sleep 3

    file = File.open(File.join(dir_path, filename))
    @chart.photo = file
    file.close


    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chart_params
      params.require(:chart).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Charts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charts.each do |chart| %>
      <tr>
        <td><%= chart.title %></td>
        <td><%= chart.description %></td>
        <td><%= link_to 'Show', chart %></td>
        <td><%= link_to 'Edit', edit_chart_path(chart) %></td>
        <td><%= link_to 'Destroy', chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chart', new_chart_path %>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chart.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @chart.description %>
</p>


<%= image_tag @chart.photo.url %>


<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebGnuploter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>